#!/usr/bin/env python3
"""
MCP SERVER GENERATOR - Semantic Refactoring Extract
Split from generate_mcp_servers.py based on semantic analysis

🧠 SEMANTIC REFACTORING: Extracted MCP server generation logic
- Responsible for: FastMCP server code generation, templates, file writing
- Bridges: mcp_servers concept (focused responsibility)
"""

import os
import time
from typing import Dict, Optional

class MCPServerGenerator:
    """Generates MCP server code for buffer agents"""
    
    def __init__(self):
        self.project_dir = "/Users/jonathanhill/src/redis-ai-challenge"
        print("🏭 MCP SERVER GENERATOR ACTIVE")
    
    def generate_agent_server(self, agent: Dict) -> Optional[Dict]:
        """Generate MCP server code for a specific buffer agent"""
        
        agent_name = agent['name']
        org_file = agent['info'].get('org_file', 'unknown.org')
        capabilities = agent['capabilities']
        
        server_code = f'''#!/usr/bin/env python3
"""
{agent_name}_mcp_server.py - Auto-generated MCP Server
Buffer Agent for: {org_file}
Generated by Living Knowledge Organism - Semantic Refactoring Enhanced
"""

from fastmcp import FastMCP
import redis
import json
import time
import os

mcp = FastMCP("{agent_name.replace('_', '-')}")
r = redis.Redis(host='localhost', port=6379, decode_responses=True)

@mcp.tool()
def monitor_buffer_state() -> str:
    """Monitor the state of this buffer agent's org file"""
    
    org_file = "{org_file}"
    agent_name = "{agent_name}"
    
    try:
        if os.path.exists(org_file):
            stat = os.stat(org_file)
            file_size = stat.st_size
            last_modified = stat.st_mtime
            
            with open(org_file, 'r') as f:
                content = f.read()
                line_count = len(content.split('\\n'))
                char_count = len(content)
            
            state = {{
                "file_exists": True,
                "size": file_size,
                "lines": line_count,
                "characters": char_count,
                "last_modified": last_modified,
                "last_check": time.time(),
                "semantic_refactored": True  # Mark as refactored version
            }}
            
            r.hset(f"agent:{{agent_name}}:state", mapping=state)
            
            return f"""📄 BUFFER STATE (Semantic Refactored): {{agent_name}}
File: {{org_file}}
Size: {{file_size}} bytes ({{line_count}} lines)
Characters: {{char_count}}
Last Modified: {{time.ctime(last_modified)}}
Status: ✅ Active and monitored (Enhanced Architecture)
"""
        else:
            return f"❌ Org file not found: {{org_file}}"
            
    except Exception as e:
        return f"❌ Error monitoring buffer: {{e}}"

@mcp.tool()
def analyze_buffer_content() -> str:
    """Analyze the content of this buffer agent's org file"""
    
    org_file = "{org_file}"
    agent_name = "{agent_name}"
    
    try:
        with open(org_file, 'r') as f:
            content = f.read()
        
        analysis = {{
            "has_title": "#+TITLE:" in content,
            "heading_count": content.count('* '),
            "link_count": content.count('[['),
            "todo_count": content.count('TODO'),
            "done_count": content.count('DONE'),
            "code_blocks": content.count('#+BEGIN_SRC'),
            "word_count": len(content.split()),
            "semantic_version": True  # Mark as semantically enhanced
        }}
        
        r.hset(f"agent:{{agent_name}}:analysis", mapping=analysis)
        
        return f"""🔍 CONTENT ANALYSIS (Semantic Enhanced): {{agent_name}}
Title Present: {{analysis['has_title']}}
Headings: {{analysis['heading_count']}}
Links: {{analysis['link_count']}}
TODOs: {{analysis['todo_count']}}
DONEs: {{analysis['done_count']}}
Code Blocks: {{analysis['code_blocks']}}
Words: {{analysis['word_count']}}
Architecture: ✅ Semantically optimized

✅ Analysis stored in knowledge graph
"""
        
    except Exception as e:
        return f"❌ Error analyzing content: {{e}}"

@mcp.tool()
def semantic_server_status() -> str:
    """Report status of this semantically refactored server"""
    
    agent_name = "{agent_name}"
    
    return f"""🧠 SEMANTIC SERVER STATUS: {{agent_name}}
Architecture: ✅ Refactored based on semantic analysis
Coupling: ✅ Reduced from 5 concepts to focused responsibility
Performance: ✅ Optimized through semantic insights
Integration: ✅ Enhanced coordination patterns

This server was generated by semantic intelligence recommendations!
"""

if __name__ == "__main__":
    mcp.run()
'''
        
        # Write server file
        server_filename = f"{agent_name}_mcp_server_semantic.py"
        server_path = f"{self.project_dir}/{server_filename}"
        
        try:
            with open(server_path, 'w') as f:
                f.write(server_code)
            
            return {
                "agent": agent_name,
                "server_file": server_path,
                "capabilities": list(capabilities.keys()) + ["semantic_enhanced"],
                "generated": True,
                "semantic_refactored": True
            }
        except Exception as e:
            print(f"❌ Error generating server for {agent_name}: {e}")
            return None