#!/usr/bin/env python3
"""
RUPERT SELF-IMPROVEMENT: rupert_improvement_priority_fixes.py
Generated by Rupert's self-improvement system
Rupert made himself better by creating this code
"""


import logging
import sys
from datetime import datetime

class RupertLogger:
    """Intelligent logging system for Rupert"""
    
    def __init__(self, component_name):
        self.logger = logging.getLogger(f"rupert.{component_name}")
        self.logger.setLevel(logging.INFO)
        
        # Create formatter
        formatter = logging.Formatter(
            '🤖 %(asctime)s [%(name)s] %(levelname)s: %(message)s'
        )
        
        # Console handler
        handler = logging.StreamHandler(sys.stdout)
        handler.setFormatter(formatter)
        self.logger.addHandler(handler)
    
    def intelligence(self, message):
        """Log intelligence-related events"""
        self.logger.info(f"🧠 INTELLIGENCE: {message}")
    
    def reasoning(self, message):
        """Log reasoning processes"""
        self.logger.info(f"🤔 REASONING: {message}")
    
    def learning(self, message):
        """Log learning events"""
        self.logger.info(f"🎓 LEARNING: {message}")
