port 6381
dir /Users/jonathanhill/src/redis-ai-challenge/redis_instances/learning_data
dbfilename dump.rdb
daemonize yes
pidfile /Users/jonathanhill/src/redis-ai-challenge/redis_instances/learning_data/redis_6381.pid
logfile /Users/jonathanhill/src/redis-ai-challenge/redis_instances/learning_data/redis_6381.log