port 6380
dir /Users/jonathanhill/src/redis-ai-challenge/redis_instances/emacs_state
dbfilename dump.rdb
daemonize yes
pidfile /Users/jonathanhill/src/redis-ai-challenge/redis_instances/emacs_state/redis_6380.pid
logfile /Users/jonathanhill/src/redis-ai-challenge/redis_instances/emacs_state/redis_6380.log